use std::path::PathBuf;
use clap::Parser;
use common::tracing::LoggingArgs;
use gen_proof::args::Input;

/// Off-chain verification, that proof was generated by specific script configuration.
#[derive(Parser, Debug)]
pub struct Args {
    #[command(flatten)]
    pub logging: LoggingArgs,

    /// Path to script configuration
    #[arg(long, env = "CONFIG_PATH", default_value = "./artifacts/config.json")]
    pub config: PathBuf,

    /// Hex string proof, generated with same script configuration
    #[arg(long, env = "VERIFY_PROOF")]
    pub proof: String,

    #[command(flatten)]
    pub input: Input,
}